### ISSUE TITLE
Cannot find module 'reInterval'

### ISSUE THREAD

**Issue by Satyricon** [apparatus/Kafkaesque#24]
Hi! I tried to use your module but it gives the following error:

```
module.js:457
    throw err;
    ^

Error: Cannot find module 'reInterval'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/PATH_TO_PROJECT/node_modules/kafkaesque/lib/kafkaesque.js:21:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

`npm install` runs without problems and I can see reinterval under node_modules. Tried with node 6.2.1 and 6.5.0

**Comment by healyje** [comment]
The npm package hasn't been updated with the github code. The kafkaesque.js code pulled down from npm has this require in it:

var reInterval = require('reInterval');

the same file here in github has:

var reInterval = require('reinterval'); ### note the casing on the 'i' in reinterval

Apparatus, could you resync npm and githup - thanks....

**Comment by GlenTiki** [comment]
Resolved. Thanks @healyje! 👍
